### ISSUE TITLE
Please resubmit tt05-collatz to Tiny Tapeout 05

### ISSUE THREAD

**Issue by urish** [rtfb/tt05-collatz#1]
Hi Vytautas,

We have done some internal changes to Tiny Tapeout 05 that require resubmission of the project to the shuttle. There are two only two steps:

1. Rerun the [GDS workflow](https://github.com/rtfb/tt05-collatz/actions/workflows/gds.yaml) in this repo and wait for it to complete (or, if you create a new commit, that'll also start the GDS workflow)
2. Go to https://app.tinytapeout.com/ (sign in as needed), then choose your project from the list and click the blue "SUBMIT A NEW REVISION" button

Thanks!

**Comment by rtfb** [comment]
Thanks Uri! Doing that now. An excellent opportunity to find and fix a typo in the readme :-)
